[package]
name = "eiger-code-challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quinn = "0.10.1"
rcgen = "0.11.1"
rustls = "0.21.5"
tokio = "1.29.1"
bytes = "1.4.0"